apiVersion: v2
name: renovate
description: Renovate with github app install token
type: application
# renovate: image=renovate/renovate
version: 41.168.2
# renovate: image=renovate/renovate
appVersion: 41.168.2
