apiVersion: v2
name: renovate
description: Renovate with github app install token
type: application
# renovate: image=renovate/renovate
version: 42.95.4
# renovate: image=renovate/renovate
appVersion: 42.95.4
