apiVersion: v2
name: renovate
description: Renovate with github app install token
type: application
# renovate: image=renovate/renovate
version: 43.46.6
# renovate: image=renovate/renovate
appVersion: 43.46.6
